[package]
name = "mp3-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
cpal = "0.15"
crossbeam-queue = "0.3"
